# reusable-workflows/.github/workflows/build-and-test.yml

name: Build and Tests

on:
  workflow_call:
    inputs:
      project-dir:
        type: string
        required: true
    secrets:
      token:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install
        working-directory: ${{ inputs.project-dir }}

      - name: Run tests
        run: npm test
        working-directory: ${{ inputs.project-dir }}
